(ns rest-api.classes.laboratory.widgets.strains
  (:require
    [datomic.api :as d]
    [rest-api.formatters.object :as obj :refer [pack-obj]]))

(defn strains [laboratory]
  (let [db (d/entity-db laboratory)
        data (->> (d/q '[:find [?strent ...]
                         :in $ ?laboratory
                         :where
                         [?strent :strain/id ?strainid]
                         [(clojure.string/starts-with? ?strainid ?laboratory)]]
                       db (:laboratory/id laboratory))
                  (map (fn [strent]
                         (let [strain (d/entity db strent)]
                           {:strain (pack-obj "strain" strain)
                            :genotype (:strain/genotype strain)})))
                  (seq))]
    {:data data
     :description "strains generated by laboratory"}))

(def widget
  {:strains strains})
