version: "3.7"
services:
  wormbase_api:
    image: 357210185381.dkr.ecr.us-east-1.amazonaws.com/wormbase/rest:1.5.7b
    ports:
      - "80:3000"
    environment:
      - WB_DB_URI=${WB_DB_URI}
      - PORT=3000
