(ns rest-api.classes.protein.widgets.sequences
  (:require
    [clojure.java.jdbc :as jdbc]
    [rest-api.db.sequence :as wb-seq]
    [rest-api.classes.generic-fields :as generic])
 (:import (org.biojava.nbio.core.sequence ProteinSequence DNASequence ))
 (:import (org.biojava.bio.proteomics.IsoelectricPointCalc getPI ))
  )


(defn x [q]
  (do (println (.toString (getPI (new ProteinSequence "MQCSPDPEDLLIVPTHDIPSYDESLDPFGPEGHLSLDIDCFSKFMSRSDNRIMSKPIIVRGIPWRILAICRGSRNQQGSRHSMNSRVNRSNFNFGFFLQCNNDELLQKRGMWRCYGTAVLEVLNADGPSIQKKIHHSFHNTEVDWGFSNYDQYDTLCNPKDGYVVNDTIKLRCRFTADVPTGANYMWDSKRHTGCIGLRNQGATCYMNSILQSFYFTTGFRRAVYNMDVGTEPNESNIVLAMQRVFYELQMASEAVETNSLTRAFGWDKLDAFNQHDVQEFCRVLLDNLETKMKGTSEEKSIPNLFRGNMKSYIKCLDVDYESSRTESFYDVQLNVLGMDSLERAFEAYTTSEILDDENKYDAGDHGLQRAEKGVKFVELPPILHVQLMRFQYCGVEQKINERFSFPEKMNLASCCELGPMLTEEDCVYSLHAVLVHSGEFHGGHYVTYINVNLHESAVDPTSSAKWCKFDDDVVSRTTTDDAIVSNFGGEKTMNSSAYMLVYVRDNAIDQFLAPIPDSQIPQSVSRTFEMERLHRNREKKKLEEEQLCMGIVLVTPDIVASNHSFDLVDQSIVHDSIPHETVWKHMFTAELYQFVHDRLFEKSAMQKIDMFDSDDEARQARRDNLRRIKSKKFNFRLWRMTDSYSLERTTQKLTSRLRPSEFIDCKTDTRLDTLLSQDFETIYVEFSNNIERPLCEYDTARDLLFFVKYYDTMTDKFTIIGHTMFDCHKRFNLYRSMLCEMIGLPADTELKYYMEHAASYLELVDLTQNYSIGRLVEEQDGGILVVEKVETSTSTQNAKQKMNELFLDVEVEFVQSFYNKKPEEEPFEQFVKRICLDDKLFTVAEEIGARLNVDPKKVLIWTRVSGSRFEPFFDDYMLNTCKGLMTRPVHDPRAYKRYRVQYAIMPFDIDEISKHRIQTKLFWQLPNGHVEELTLFPLKEGTVIDIINEAKRYYPFVEGGSGKFRLLQIGAPPLSNQRVYQIYGENTLISDLDQRTMYKLALHCRLEEVPIDELDMSPGEFLCPVVHFDREPTKLFGLSFVIKIRNNELMTEVRDRLRRKLNDVSDADFAKYKFALLSRDKLCRTIEFNNGEKVNLADMANQTTGVPQVYIGLDHKSPIQHSSEAAIRILN"))))))

(defn estimated-isoelectric-point [p]
  {:data nil ; should use org.biojava.bio.proteomics.IsoelectricPointCalc see: http://biojava.org/wiki/BioJava%3ACookbook%3AProteomics
             ; or try http://biojava.org/wiki/BioJava:CookBook:AAPROP:main
   :description "the estimated isoelectric point of the protein"})

;; from wormbase :
;;       "estimated_isoelectric_point" : {
;;          "data" : "5.47",
;;          "description" : "the estimated isoelectric point of the protein",
;;          "peptide" : "MQCSPDPEDLLIVPTHDIPSYDESLDPFGPEGHLSLDIDCFSKFMSRSDNRIMSKPIIVRGIPWRILAICRGSRNQQGSRHSMNSRVNRSNFNFGFFLQCNNDELLQKRGMWRCYGTAVLEVLNADGPSIQKKIHHSFHNTEVDWGFSNYDQYDTLCNPKDGYVVNDTIKLRCRFTADVPTGANYMWDSKRHTGCIGLRNQGATCYMNSILQSFYFTTGFRRAVYNMDVGTEPNESNIVLAMQRVFYELQMASEAVETNSLTRAFGWDKLDAFNQHDVQEFCRVLLDNLETKMKGTSEEKSIPNLFRGNMKSYIKCLDVDYESSRTESFYDVQLNVLGMDSLERAFEAYTTSEILDDENKYDAGDHGLQRAEKGVKFVELPPILHVQLMRFQYCGVEQKINERFSFPEKMNLASCCELGPMLTEEDCVYSLHAVLVHSGEFHGGHYVTYINVNLHESAVDPTSSAKWCKFDDDVVSRTTTDDAIVSNFGGEKTMNSSAYMLVYVRDNAIDQFLAPIPDSQIPQSVSRTFEMERLHRNREKKKLEEEQLCMGIVLVTPDIVASNHSFDLVDQSIVHDSIPHETVWKHMFTAELYQFVHDRLFEKSAMQKIDMFDSDDEARQARRDNLRRIKSKKFNFRLWRMTDSYSLERTTQKLTSRLRPSEFIDCKTDTRLDTLLSQDFETIYVEFSNNIERPLCEYDTARDLLFFVKYYDTMTDKFTIIGHTMFDCHKRFNLYRSMLCEMIGLPADTELKYYMEHAASYLELVDLTQNYSIGRLVEEQDGGILVVEKVETSTSTQNAKQKMNELFLDVEVEFVQSFYNKKPEEEPFEQFVKRICLDDKLFTVAEEIGARLNVDPKKVLIWTRVSGSRFEPFFDDYMLNTCKGLMTRPVHDPRAYKRYRVQYAIMPFDIDEISKHRIQTKLFWQLPNGHVEELTLFPLKEGTVIDIINEAKRYYPFVEGGSGKFRLLQIGAPPLSNQRVYQIYGENTLISDLDQRTMYKLALHCRLEEVPIDELDMSPGEFLCPVVHFDREPTKLFGLSFVIKIRNNELMTEVRDRLRRKLNDVSDADFAKYKFALLSRDKLCRTIEFNNGEKVNLADMANQTTGVPQVYIGLDHKSPIQHSSEAAIRILN"
;;       },


(defn estimated-molecular-weight [p]
  {:data (when-let [mw (:protein.molecular-weight/float
           (first
             (:protein/molecular-weight p)))]
           (format "%.1f" mw))
   :description "the estimated molecular weight of the protein"})

(defn amino-acid-composition [p]
  {:data (keys p)
   :d (:db/id p) ; bioperl uses seqStats
   :description "The amino acid composition of the protein"})

(defn sequence-fn [p]
  {:data (when-let [h (:protein/peptide p)]
           {:length (:protein.peptide/length h)
            :sequences (:peptide/sequence
                         (:protein.peptide/peptide h))
            :s (println (->> (:peptide/sequence
                         (:protein.peptide/peptide h))
;;                          (new IsoelectricPointCalc)
                             ))
            :type "aa"})
   :description "the peptide sequence of the protein"})

(def widget
    {:name generic/name-field
     :estimated_isoelectric_point estimated-isoelectric-point
     :estimated_molecular_weight estimated-molecular-weight
     :amino_acid_composition amino-acid-composition
     :x x
     :sequence sequence-fn})
